name: API Test Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Run ALL tests (simpler for interview)
      - name: Run Tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testng-regression.xml

      # Generate Allure report
      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:report

      # Prepare Pages artifact
      - name: Prepare Pages
        run: |
          mkdir public
          cp -r target/site/allure-maven-plugin/* public/

      # Upload to GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: test-and-report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4